/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//The SalesAdd page allows the user to add a new sale to the database.

import java.sql.*;
import javax.swing.*;
import java.math.BigDecimal;
/**
 *
 * @author Max
 */
public class SalesAdd extends javax.swing.JFrame {

    /**
     * Creates new form InventoryUpdate
     */
    public SalesAdd() {
        initComponents();
    }

    /** 
    * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddIngredient = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtSaleDate = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        lblProductID = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblUnitCost = new javax.swing.JLabel();
        lblSaleAmount = new javax.swing.JLabel();
        txtSaleAmount = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAddIngredient.setText("Record Sale");

        txtProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIDActionPerformed(evt);
            }
        });

        txtSaleDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaleDateActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        lblProductID.setText("ProductID");

        lblQuantity.setText("Quantity Sold");

        lblUnitCost.setText("Sale Date");

        lblSaleAmount.setText("Sale Amount");

        txtSaleAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaleAmountActionPerformed(evt);
            }
        });

        btnClose.setText("x");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProductID)
                    .addComponent(lblQuantity)
                    .addComponent(lblUnitCost)
                    .addComponent(lblSaleAmount))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSaleDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddIngredient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(AddButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAddIngredient))
                    .addComponent(btnClose))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductID)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaleDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnitCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaleAmount)
                    .addComponent(txtSaleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(AddButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        //this method adds the data recorded in the fields to the database

        //retrieve & validate data from GUI forms using ValidationRoutines
        Integer productId = ValidationRoutines.parseInteger(txtProductID.getText(), "product ID", this);
        if (productId == null) {
            return;
        }

        Integer quantitySold = ValidationRoutines.parseInteger(txtQuantity.getText(), "quantity sold", this);
        if (quantitySold == null || quantitySold <= 0) {
            return;
        }

        BigDecimal totalSaleAmount = ValidationRoutines.parseBigDecimal(txtSaleAmount.getText(), "total sale amount", this);
        if (totalSaleAmount == null) {
            return;
        }

        String saleDate = txtSaleDate.getText();
        if (!ValidationRoutines.isValidString(saleDate, "sale date", this)) {
            return;
        }


        String insertSaleQuery = "INSERT INTO tblSales (ProductID, QuantitySold, SaleDate, TotalSaleAmount) VALUES (?, ?, ?, ?)"; //make statement with placeholders
        String updateProductQuery = "UPDATE tblProducts SET ProductQuantity = ProductQuantity - ? WHERE ProductID = ?"; //make placeholder statement for decreasing product quantity

        try {
            // Open a connection and create the prepared statements
            Connection conn = DriverManager.getConnection("jdbc:mysql://computing.gfmat.org:3306/BMSProject", "MBrain", "hkFfdZ2X3N"); //make connection to database
            PreparedStatement insertSaleStmt = conn.prepareStatement(insertSaleQuery); //prevent SQL injection
            PreparedStatement updateProductStmt = conn.prepareStatement(updateProductQuery);//prevent SQL injection

            insertSaleStmt.setInt(1, productId);
            insertSaleStmt.setInt(2, quantitySold);
            insertSaleStmt.setString(3, saleDate);
            insertSaleStmt.setBigDecimal(4, totalSaleAmount);
            //set placeholder values to form data
            insertSaleStmt.executeUpdate();
            //execute insert statement to add new record
            updateProductStmt.setInt(1, quantitySold);
            updateProductStmt.setInt(2, productId);
            //set placeholder values to decrease product quantity
            updateProductStmt.executeUpdate();
            //execute update statement to decrease quantity
            JOptionPane.showMessageDialog(this, "Sale recorded successfully."); //display success msg
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error adding sale record." + ex.getMessage()); //display error msg
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void txtSaleDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaleDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaleDateActionPerformed

    private void txtSaleAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaleAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaleAmountActionPerformed

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIDActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngredientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngredientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngredientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngredientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngredientUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblAddIngredient;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSaleAmount;
    private javax.swing.JLabel lblUnitCost;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSaleAmount;
    private javax.swing.JTextField txtSaleDate;
    // End of variables declaration//GEN-END:variables
}
